// Relative .ts import keeps this module runnable under `node --test`.
import { defineCopy } from "../../core/i18n/t.ts"

/**
 * Settings module copy (general, appearance, team, activity). English is
 * the source; es-MX follows sentence case. Keys are English identifiers
 * under `settings.`; components resolve them with `useT(settingsCopy)`.
 */
export const settingsCopy = defineCopy({
  en: {
    "settings.appearance.intake.1.title": "One accent colour",
    "settings.appearance.intake.1.body": "Their primary, as a hex or an oklch triplet. We read its hue and chroma and place every other value from there.",
    "settings.appearance.intake.1.example": "e.g. #2D5BFF → hue 262, chroma .19",
    "settings.appearance.intake.2.title": "One neutral direction",
    "settings.appearance.intake.2.body": "Warm, cool, or true neutral — a single grey from their palette is enough to infer it.",
    "settings.appearance.intake.2.example": "e.g. #6B6560 reads warm",
    "settings.appearance.intake.3.title": "Two typefaces",
    "settings.appearance.intake.3.body": "A display and body face, and a mono for numerals. If they have no mono, say so and keep ours.",
    "settings.appearance.intake.3.example": "e.g. Figtree + IBM Plex Mono",
    "settings.appearance.intake.4.title": "Two weights",
    "settings.appearance.intake.4.body": "Which weight of that face reads as bold, and which as semibold. Faces differ; the scale does not.",
    "settings.appearance.intake.4.example": "e.g. 700 and 600",
    "settings.appearance.intake.5.title": "Logo, two files",
    "settings.appearance.intake.5.body": "One for light grounds, one for dark. SVG preferred, and it has to stay legible at 30px tall.",
    "settings.appearance.intake.5.example": "e.g. logo-light.svg, logo-dark.svg",
    "settings.appearance.intake.6.title": "Favicon",
    "settings.appearance.intake.6.body": "A square mark, not the full wordmark — it renders at 16px in a browser tab and anything with words turns to mush. SVG plus a 512px PNG fallback.",
    "settings.appearance.intake.6.example": "e.g. favicon.svg, icon-512.png",
    "settings.appearance.rule.surfaces": "Five steps on the neutral hue: page ground, shell, card, hairline, border. On dark they are redrawn as peers, never inverted.",
    "settings.appearance.rule.text": "Four fixed lightness steps. The gap between secondary and muted is what keeps enabled and disabled apart.",
    "settings.appearance.rule.accentText": "The accent minus .08 lightness, because a fill-bright colour fails contrast at 13px.",
    "settings.appearance.rule.series": "One hue, five steps of falling lightness and chroma. Charts use them in rank order, never as categories.",
    "settings.appearance.rule.semantics": "Hues fixed at 147, 78 and 25 so green is green in every brand — only the chroma follows the accent.",
    "settings.appearance.rule.lead": "The emphasised panel is a tint of the accent, not a black slab, so it holds up in a pale layout.",
    "settings.appearance.toast.uploadFailed": "Upload failed",
    "settings.appearance.toast.faviconUpdated": "Favicon updated",
    "settings.appearance.toast.logoUpdated": "Logo updated",
    "settings.appearance.toast.removed": "Removed",
    "settings.appearance.toast.removeFailed": "Could not remove",
    "settings.appearance.eyebrow": "Workspace · brand variables",
    "settings.appearance.title": "Appearance & brand",
    "settings.appearance.status.saving": "Saving…",
    "settings.appearance.status.saved": "Saved",
    "settings.appearance.status.failed": "Couldn't save",
    "settings.appearance.intro": "The values a brand supplies. Everything else in the product is computed from them, in both themes.",
    "settings.appearance.readOnly": "You can view these settings, but only an owner or admin can change them.",
    "settings.appearance.askTitle": "What to ask a brand for",
    "settings.appearance.askBody": "Six things, and only six. Everything on this page — every surface, all four text steps, the chart ramp, green, amber, red, both themes — is computed from them. Asking for a full palette produces drift, because somebody eventually picks the wrong grey.",
    "settings.appearance.doNotAsk": "Do not ask for",
    "settings.appearance.doNotAskBody": "Hover and pressed states, disabled greys, chart palettes, tints, dark-mode equivalents, corner radii, spacing, or per-component colour. The system owns all of it, and a brand that insists on its own radius is asking for a different product.",
    "settings.appearance.mode.title": "Default appearance",
    "settings.appearance.mode.body": "The appearance new sessions start in: light, dark, or the device setting. Each person can still switch from the account menu.",
    "settings.appearance.logo.title": "Brand mark",
    "settings.appearance.logo.body": "Drops into the rail at exactly 30px tall, up to 176px wide. Supply a horizontal lockup as SVG (or PNG at 2×, ≥ 352×60) with a transparent background and no built-in padding — a stacked or square-only mark renders tiny at this height. Supply artwork for both grounds — light and dark are peer palettes, so provide a version legible on each, not one recolored file.",
    "settings.appearance.logo.light": "Logo · light ground",
    "settings.appearance.logo.lightHint": "Shown on the light theme rail. Dark or full-color artwork that holds up on near-white.",
    "settings.appearance.logo.dark": "Logo · dark ground",
    "settings.appearance.logo.darkHint": "Shown on the dark theme rail. Light artwork that holds up on near-black.",
    "settings.appearance.logo.favicon": "Favicon",
    "settings.appearance.logo.faviconHint": "Square mark only. It renders at 16px, so a wordmark turns to mush.",
    "settings.appearance.logo.upload": "Upload",
    "settings.appearance.logo.replace": "Replace",
    "settings.appearance.logo.remove": "Remove",
    "settings.appearance.logo.none": "None",
    "settings.appearance.color.title": "Colour",
    "settings.appearance.color.body": "Two hues and two chroma levels. Every surface, text step, chart step, and status colour is computed from these, in both themes.",
    "settings.appearance.color.accentHue": "Accent hue",
    "settings.appearance.color.accentChroma": "Accent chroma",
    "settings.appearance.color.neutralHue": "Neutral hue",
    "settings.appearance.color.neutralChroma": "Neutral chroma",
    "settings.appearance.color.semanticChroma": "Semantic chroma",
    "settings.appearance.color.semanticHint": "Controls the intensity of success, warning, and error colours. Their hues stay fixed.",
    "settings.appearance.color.success": "Success",
    "settings.appearance.color.warning": "Warning",
    "settings.appearance.color.error": "Error",
    "settings.appearance.color.hue": "Hue {n}",
    "settings.appearance.color.chroma": "Chroma {n}",
    "settings.appearance.color.neutralHueSwatch": "Neutral hue {n}",
    "settings.appearance.color.neutralChromaSwatch": "Neutral chroma {n}",
    "settings.appearance.contrast.title": "Contrast falls short with these seeds",
    "settings.appearance.contrast.line": "{pair}, {mode} theme: {ratio}:1 (needs {minimum}:1)",
    "settings.appearance.contrast.pair.inkOnAccent": "Button text on accent",
    "settings.appearance.contrast.pair.accentTextOnCard": "Accent text on card",
    "settings.appearance.contrast.mode.light": "light",
    "settings.appearance.contrast.mode.dark": "dark",
    "settings.appearance.type.title": "Type",
    "settings.appearance.type.body": "Sizes and tracking are fixed by the system. A brand supplies the faces and the two emphasis weights.",
    "settings.appearance.type.display": "Display and body",
    "settings.appearance.type.mono": "Mono",
    "settings.appearance.type.bold": "Bold weight",
    "settings.appearance.type.semibold": "Semibold weight",
    "settings.appearance.shape.title": "Shape",
    "settings.appearance.shape.tag": "Interface setting",
    "settings.appearance.shape.body": "Three radii: outer panels, inner panels, controls. Changing these changes the product, not the brand — move them deliberately.",
    "settings.appearance.preview.light": "Light",
    "settings.appearance.preview.dark": "Dark",
    "settings.appearance.preview.live": "Live preview",
    "settings.appearance.preview.logoAlt": "{ground} ground logo",
    "settings.appearance.preview.primary": "Primary",
    "settings.appearance.preview.secondary": "Secondary",
    "settings.appearance.preview.settled": "Settled",
    "settings.appearance.preview.waiting": "Waiting",
    "settings.appearance.preview.failed": "Failed",
    "settings.appearance.presets": "Presets",
    "settings.appearance.preset.base.hint": "cool grey, blue",
    "settings.appearance.preset.electric.hint": "near-black, bright green fill",
    "settings.appearance.preset.green.hint": "sage, warm forest neutrals",
    "settings.appearance.custom.title": "Custom",
    "settings.appearance.custom.hint": "two seeds, rest derived",
    "settings.appearance.custom.accent": "Accent",
    "settings.appearance.custom.neutral": "Neutral grey",
    "settings.appearance.custom.picker": "{seed} colour picker",
    "settings.appearance.custom.invalidHex": "Use a hex colour, like #2F4FD0.",
    "settings.appearance.derived": "How the rest is derived",
    "settings.appearance.derivedBody": "Colour is built in oklch, where the first number is perceived lightness. That is what lets one rule hold for every hue instead of being eyeballed per brand.",
    "settings.appearance.tokens": "Resolved tokens",
    "settings.appearance.restore": "Reset to last saved",
    "settings.appearance.restoreTitle": "Restores the last successfully saved values (not the starter defaults)",
    "settings.appearance.error.notAdmin": "Only an owner or admin can change workspace branding.",
    "settings.appearance.error.appearance": "Default appearance must be light, dark, or system.",
    "settings.appearance.error.colorNaN": "One of the colour values is not a number.",
    "settings.appearance.error.font": "Pick a display face from the list.",
    "settings.appearance.error.mono": "Pick a mono face from the list.",
    "settings.appearance.error.bold": "Pick a bold weight from the list.",
    "settings.appearance.error.semibold": "Pick a semibold weight from the list.",
    "settings.appearance.error.radii": "Radii must be whole numbers between 0 and 34.",
    "settings.appearance.error.saveFailed": "Could not save — nothing was changed. Try again.",
    "settings.appearance.error.assetKind": "Unknown asset kind.",
    "settings.appearance.error.noFile": "Choose a file first.",
    "settings.appearance.error.format": "That format is not supported — use SVG or PNG.",
    "settings.appearance.error.tooLarge": "Keep artwork under 2MB.",
    "settings.appearance.error.uploadFailed": "Upload failed — nothing was changed.",
    "settings.appearance.error.notLinked": "Upload stored but not linked — try again.",
    "settings.appearance.error.removeFailed": "Could not remove — try again.",

    "settings.team.toast.failed": "That did not work",
    "settings.team.summary.members.one": "{n} member",
    "settings.team.summary.members.other": "{n} members",
    "settings.team.summary.admins.one": "{n} admin",
    "settings.team.summary.admins.other": "{n} admins",
    "settings.team.summary.invitations.one": "{n} pending invitation",
    "settings.team.summary.invitations.other": "{n} pending invitations",
    "settings.team.summary.yourRole": "your role: {role}",
    "settings.team.column.member": "Member",
    "settings.team.column.role": "Role",
    "settings.team.roleFor": "Role for {email}",
    "settings.team.toast.roleUpdated": "Role updated",
    "settings.team.column.joined": "Joined",
    "settings.team.remove.title": "Remove {email}?",
    "settings.team.remove.body": "They lose access to this workspace immediately. Their account and anything they created stay intact, and they can be invited again later.",
    "settings.team.remove.confirm": "Remove from workspace",
    "settings.team.remove.cancel": "Keep them",
    "settings.team.remove.label": "Remove {email}",
    "settings.team.toast.memberRemoved": "Member removed",
    "settings.team.eyebrow": "Workspace · people",
    "settings.team.title": "Team & permissions",
    "settings.team.invite": "Invite member",
    "settings.team.empty.title": "No members yet",
    "settings.team.empty.body": "Invite the first person to this workspace.",
    "settings.team.pending": "Pending invitations",
    "settings.team.invitedAs": "as {role} · expires {date}",
    "settings.team.invitedChip": "Invited",
    "settings.team.toast.resent": "Invitation resent — the old link stopped working",
    "settings.team.resend": "Resend",
    "settings.team.revoke.title": "Revoke the invitation for {email}?",
    "settings.team.revoke.body": "The emailed link stops working immediately. You can invite them again at any time.",
    "settings.team.revoke.confirm": "Revoke it",
    "settings.team.toast.revoked": "Invitation revoked",
    "settings.team.revoke": "Revoke",
    "settings.team.roles.title": "Roles & permissions",
    "settings.team.roles.body": "Roles control what people can manage in this workspace.",
    "settings.team.roles.ownerNote": "The owner cannot be demoted or removed — a workspace always keeps a full administrator.",
    "settings.team.dialog.error": "Could not send the invitation.",
    "settings.team.dialog.sent": "Invitation sent to {email}",
    "settings.team.dialog.title": "Invite to the workspace",
    "settings.team.dialog.body": "They get a branded email with a single-use link that signs them in — no password.",
    "settings.team.dialog.email": "Work email",
    "settings.team.dialog.emailPlaceholder": "name@company.com",
    "settings.team.dialog.role": "Role",
    "settings.team.dialog.cancel": "Cancel",
    "settings.team.dialog.sending": "Sending…",
    "settings.team.dialog.send": "Send invite",
    "settings.team.error.notAdmin": "Only an owner or admin can invite people.",
    "settings.team.error.roleNotAllowed": "You can invite people as {allowed} — not {role}.",
    "settings.team.error.assignNotAllowed": "You can assign {allowed} — not {role}.",
    "settings.team.error.alreadyMember": "{email} is already a member of this workspace.",
    "settings.team.error.alreadyInvited": "{email} already has a pending invitation — resend it instead.",
    "settings.team.error.createFailed": "Could not create the invitation. Try again.",
    "settings.team.error.emailFailed": "The email could not be sent.",
    "settings.team.error.gone": "That invitation no longer exists.",
    "settings.team.error.notPending": "Only pending invitations can be resent.",
    "settings.team.error.resendFailed": "Could not resend — check your access and try again.",
    "settings.team.error.revokeFailed": "Could not revoke — it may already be accepted or gone.",
    "settings.team.error.unknownRole": "Unknown role.",
    "settings.team.error.ownerRole": "The owner's role cannot be changed.",
    "settings.team.error.cannotManage": "You cannot manage that member.",
    "settings.team.error.roleUnchanged": "The role was not changed — check your access.",
    "settings.team.error.ownerRemove": "The owner cannot be removed.",
    "settings.team.error.cannotRemove": "You cannot remove that member.",
    "settings.team.error.ownerLeave": "The owner cannot leave their own workspace.",
    "settings.team.error.removeFailed": "The member was not removed — check your access.",
    "settings.team.or": "or",

    "settings.activity.action.all": "All events",
    "settings.activity.action.settingsUpdated": "Settings updated",
    "settings.activity.action.brandingUpdated": "Branding updated",
    "settings.activity.action.memberAdded": "Member added",
    "settings.activity.action.roleChanged": "Role changed",
    "settings.activity.action.memberRemoved": "Member removed",
    "settings.activity.action.invitationCreated": "Invitation created",
    "settings.activity.action.invitationResent": "Invitation resent",
    "settings.activity.action.invitationRevoked": "Invitation revoked",
    "settings.activity.action.invitationAccepted": "Invitation accepted",
    "settings.activity.action.workspaceCreated": "Workspace created",
    "settings.activity.column.when": "When",
    "settings.activity.column.event": "Event",
    "settings.activity.column.summary": "What happened",
    "settings.activity.column.resource": "Resource",
    "settings.activity.eyebrow": "Workspace · audit",
    "settings.activity.title": "Activity",
    "settings.activity.intro": "Every meaningful change in this workspace · retained indefinitely",
    "settings.activity.search": "Search events",
    "settings.activity.filter.type": "Event type",
    "settings.activity.filter.actor": "Actor",
    "settings.activity.filter.everyone": "Everyone",
    "settings.activity.empty.title": "No activity yet",
    "settings.activity.empty.body": "Meaningful changes — settings, members, invitations — will appear here as they happen.",
    "settings.activity.detail.actor": "Actor",
    "settings.activity.detail.action": "Action",
    "settings.activity.detail.resource": "Resource",
    "settings.activity.detail.label": "Label",
    "settings.activity.detail.resourceId": "Resource id",
    "settings.activity.detail.eventId": "Event id",
    "settings.activity.detail.at": "At",
    "settings.activity.detail.title": "Event detail",
    "settings.activity.detail.close": "Close",
    "settings.activity.detail.changed": "What changed",
    "settings.activity.detail.metadata": "Metadata",
    "settings.activity.detail.context": "Context",
    "settings.activity.detail.before": "before",
    "settings.activity.detail.after": "after",

    "settings.general.eyebrow": "Workspace · general",
    "settings.general.title": "General",
    "settings.general.intro": "The workspace's identity and regional defaults. Visual identity lives under Appearance & brand.",
    "settings.general.readOnly": "You can view these settings, but only an owner or admin can change them.",
    "settings.general.status.saving": "Saving…",
    "settings.general.status.saved": "Saved",
    "settings.general.status.failed": "Couldn't save",
    "settings.general.workspace.title": "Workspace",
    "settings.general.workspace.body": "The name shown in the shell, the browser tab, and invitation emails — and the facts support will ask for.",
    "settings.general.workspace.name": "Workspace name",
    "settings.general.regional.title": "Regional",
    "settings.general.regional.body": "Defaults for everyone in this workspace. Each person can pick their own language from the account menu; the time zone is shared.",
    "settings.general.regional.language": "Default language",
    "settings.general.regional.hint": "Applies to new members, to anyone who has not chosen a language, and to the sign-in and invitation screens.",
    "settings.general.regional.timeZone": "Time zone",
    "settings.general.regional.timeZoneHint": "Dates, “today”, and period boundaries follow this zone for everyone, wherever they sign in from.",
    "settings.general.regional.sample": "Right now",
    "settings.general.toast.localeSaved": "Default language updated",
    "settings.general.toast.timeZoneSaved": "Time zone updated",
    "settings.general.toast.roleSaved": "Default role updated",
    "settings.general.facts.id": "Workspace id",
    "settings.general.facts.slug": "Slug",
    "settings.general.facts.created": "Created",
    "settings.general.facts.owner": "Owner",
    "settings.general.facts.members": "Members",
    "settings.general.facts.copy": "Copy",
    "settings.general.facts.copied": "Copied",
    "settings.general.facts.copyFailed": "Could not copy — select the id instead.",
    "settings.general.members.title": "Members",
    "settings.general.members.body": "Defaults for people joining this workspace. Roles themselves are managed under Team & permissions.",
    "settings.general.members.defaultRole": "Default role for invitations",
    "settings.general.members.hint": "Pre-selected in the invite dialog; the inviter can still pick another role each time.",
    "settings.general.error.invalidTimeZone": "That time zone is not recognised.",
    "settings.general.error.invalidRole": "Pick admin, member, or viewer.",
    "settings.general.error.notAdmin": "Only an owner or admin can change general settings.",
    "settings.general.error.nameRequired": "The workspace needs a name.",
    "settings.general.error.nameTooLong": "Keep the workspace name under 80 characters.",
    "settings.general.error.invalidLocale": "That language is not available.",
    "settings.general.error.saveFailed": "Could not save — nothing was changed. Try again.",
    "settings.emails.eyebrow": "Workspace · transactional email",
    "settings.emails.title": "Emails",
    "settings.emails.intro": "Every message this product sends, rendered by the code that sends it. The words come from the dictionary and the colours from the skin, so a preview here is the message that lands in an inbox.",
    "settings.emails.group.authentication": "Authentication",
    "settings.emails.group.membership": "Membership",
    "settings.emails.template.magicLink": "Sign-in link",
    "settings.emails.template.invitation": "Workspace invite",
    "settings.emails.kind.supabase": "Transactional · delivered by Supabase Auth",
    "settings.emails.kind.resend": "Transactional · sent by the app",
    "settings.emails.view.preview": "Preview",
    "settings.emails.view.html": "HTML",
    "settings.emails.view.text": "Plain text",
    "settings.emails.width.desktop": "Desktop",
    "settings.emails.width.mobile": "Mobile",
    "settings.emails.mode.light": "Light",
    "settings.emails.mode.dark": "Dark",
    "settings.emails.chrome.from": "From",
    "settings.emails.sendDetails": "Send details",
    "settings.emails.metaLabel.trigger": "Trigger",
    "settings.emails.metaLabel.delay": "Delay",
    "settings.emails.metaLabel.expiry": "Expiry",
    "settings.emails.metaLabel.delivery": "Delivery",
    "settings.emails.metaValue.signInRequested": "sign-in requested",
    "settings.emails.metaValue.invitationSent": "invitation sent",
    "settings.emails.metaValue.immediate": "immediate",
    "settings.emails.metaValue.magicLink": "15 minutes",
    "settings.emails.metaValue.invitation": "7 days",
    "settings.emails.metaValue.supabase": "Supabase Auth",
    "settings.emails.metaValue.resend": "Resend",
    "settings.emails.detail.language": "Language",
    "settings.emails.detail.branding": "Branding",
    "settings.emails.detail.sender": "Sender",
    "settings.emails.detail.subject": "Subject",
    "settings.emails.detail.preheader": "Preview line",
    "settings.emails.branding.workspace": "This workspace",
    "settings.emails.branding.project": "Project default",
    "settings.emails.brandingNote": "Sign-in mail has no workspace — the recipient may not belong to one yet. It carries the project skin and language from src/config/project.ts and ships as a static template, regenerated with pnpm build:auth-emails and pushed with the Supabase config.",
    "settings.emails.blocks": "Blocks in this email",
    "settings.emails.block.brand": "Brand row",
    "settings.emails.block.badge": "Status badge",
    "settings.emails.block.heading": "Heading",
    "settings.emails.block.paragraph": "Body",
    "settings.emails.block.code": "Code block",
    "settings.emails.block.button": "Button",
    "settings.emails.block.fallback": "URL fallback",
    "settings.emails.block.rows": "Detail table",
    "settings.emails.block.callout": "Callout",
    "settings.emails.block.secondary": "Fine print",
    "settings.emails.block.footer": "Footer",
    "settings.emails.rules": "Rules for every send",
    "settings.emails.rule.1": "One job per email. If it needs two buttons, it is two emails.",
    "settings.emails.rule.2": "The subject carries the fact, not a tease. A person should be able to act from the notification alone.",
    "settings.emails.rule.3": "Every link has a plain-text fallback URL — corporate clients strip buttons.",
    "settings.emails.rule.4": "Say why they received it, every time, in the footer.",
    "settings.emails.rule.5": "No custom properties, no external CSS. Colours are literal hex values resolved from the skin at send time.",
    "settings.emails.rule.6": "620px wide, single column, 15px body. Anything narrower than 380px is a phone and stacks.",
    "settings.emails.rule.7": "Scheduled mail can be unsubscribed; transactional mail cannot, and must not pretend otherwise.",
    "settings.emails.tokens": "Email tokens",
    "settings.emails.tokensBody": "Mail clients strip custom properties, so these are resolved to literal values at send time from the same skin the product uses.",
    "settings.emails.token.ground": "outside the card",
    "settings.emails.token.card": "the email itself",
    "settings.emails.token.inset": "tables, code",
    "settings.emails.token.accent": "buttons, links",
    "settings.emails.token.ink": "headings",
    "settings.emails.token.ink2": "body copy",
    "settings.emails.copy": "Copy",
    "settings.emails.copied": "Copied",
    "settings.emails.copyFailed": "Could not copy",
  },
  "es-MX": {
    "settings.appearance.intake.1.title": "Un color de acento",
    "settings.appearance.intake.1.body": "Su color primario, en hex o como tripleta oklch. Leemos su matiz y croma y de ahí se coloca todo lo demás.",
    "settings.appearance.intake.1.example": "p. ej. #2D5BFF → matiz 262, croma .19",
    "settings.appearance.intake.2.title": "Una dirección neutra",
    "settings.appearance.intake.2.body": "Cálida, fría o neutra pura; un solo gris de su paleta basta para inferirla.",
    "settings.appearance.intake.2.example": "p. ej. #6B6560 se lee cálido",
    "settings.appearance.intake.3.title": "Dos tipografías",
    "settings.appearance.intake.3.body": "Una para títulos y texto, y una mono para cifras. Si no tienen mono, díganlo y conservamos la nuestra.",
    "settings.appearance.intake.3.example": "p. ej. Figtree + IBM Plex Mono",
    "settings.appearance.intake.4.title": "Dos pesos",
    "settings.appearance.intake.4.body": "Qué peso de esa tipografía se lee como bold y cuál como semibold. Las tipografías cambian; la escala no.",
    "settings.appearance.intake.4.example": "p. ej. 700 y 600",
    "settings.appearance.intake.5.title": "Logo, dos archivos",
    "settings.appearance.intake.5.body": "Uno para fondos claros y otro para oscuros. De preferencia SVG, y debe seguir legible a 30px de alto.",
    "settings.appearance.intake.5.example": "p. ej. logo-light.svg, logo-dark.svg",
    "settings.appearance.intake.6.title": "Favicon",
    "settings.appearance.intake.6.body": "Un isotipo cuadrado, no el logotipo completo: se muestra a 16px en la pestaña y cualquier texto se vuelve ilegible. SVG más un PNG de 512px como respaldo.",
    "settings.appearance.intake.6.example": "p. ej. favicon.svg, icon-512.png",
    "settings.appearance.rule.surfaces": "Cinco pasos sobre el matiz neutro: fondo de página, shell, tarjeta, filete, borde. En oscuro se redibujan como pares, nunca invertidos.",
    "settings.appearance.rule.text": "Cuatro pasos fijos de luminosidad. La distancia entre secundario y atenuado es lo que separa habilitado de deshabilitado.",
    "settings.appearance.rule.accentText": "El acento menos .08 de luminosidad, porque un color brillante de relleno no pasa el contraste a 13px.",
    "settings.appearance.rule.series": "Un matiz, cinco pasos de luminosidad y croma descendentes. Las gráficas los usan por rango, nunca como categorías.",
    "settings.appearance.rule.semantics": "Matices fijos en 147, 78 y 25 para que el verde sea verde en toda marca; solo el croma sigue al acento.",
    "settings.appearance.rule.lead": "El panel enfatizado es un tinte del acento, no un bloque negro, para que funcione en un diseño claro.",
    "settings.appearance.toast.uploadFailed": "La carga falló",
    "settings.appearance.toast.faviconUpdated": "Favicon actualizado",
    "settings.appearance.toast.logoUpdated": "Logo actualizado",
    "settings.appearance.toast.removed": "Eliminado",
    "settings.appearance.toast.removeFailed": "No se pudo eliminar",
    "settings.appearance.eyebrow": "Espacio de trabajo · variables de marca",
    "settings.appearance.title": "Apariencia y marca",
    "settings.appearance.status.saving": "Guardando…",
    "settings.appearance.status.saved": "Guardado",
    "settings.appearance.status.failed": "No se pudo guardar",
    "settings.appearance.intro": "Los nueve valores que entrega una marca. Todo lo demás en el producto se calcula a partir de ellos, en ambos temas.",
    "settings.appearance.readOnly": "Puedes ver esta configuración, pero solo un propietario o administrador puede cambiarla.",
    "settings.appearance.askTitle": "Qué pedirle a una marca",
    "settings.appearance.askBody": "Seis cosas, y solo seis. Todo en esta página (cada superficie, los cuatro pasos de texto, la rampa de gráficas, verde, ámbar, rojo, ambos temas) se calcula a partir de ellas. Pedir una paleta completa produce desviaciones, porque alguien termina eligiendo el gris equivocado.",
    "settings.appearance.doNotAsk": "No pedir",
    "settings.appearance.doNotAskBody": "Estados hover y presionado, grises deshabilitados, paletas de gráficas, tintes, equivalentes en modo oscuro, radios, espaciado ni color por componente. El sistema es dueño de todo eso, y una marca que insiste en su propio radio está pidiendo otro producto.",
    "settings.appearance.mode.title": "Apariencia predeterminada",
    "settings.appearance.mode.body": "La apariencia con la que inician las sesiones nuevas: clara, oscura o la del dispositivo. Cada persona puede cambiarla desde el menú de cuenta.",
    "settings.appearance.logo.title": "Logo",
    "settings.appearance.logo.body": "Entra en la barra lateral a exactamente 30px de alto, hasta 176px de ancho. Entrega un logotipo horizontal en SVG (o PNG a 2×, ≥ 352×60) con fondo transparente y sin márgenes integrados; un isotipo apilado o cuadrado se ve diminuto a esta altura. Entrega arte para ambos fondos: claro y oscuro son paletas pares, así que da una versión legible en cada uno, no un solo archivo recoloreado.",
    "settings.appearance.logo.light": "Logo · fondo claro",
    "settings.appearance.logo.lightHint": "Se muestra en la barra del tema claro. Arte oscuro o a color que funcione sobre casi blanco.",
    "settings.appearance.logo.dark": "Logo · fondo oscuro",
    "settings.appearance.logo.darkHint": "Se muestra en la barra del tema oscuro. Arte claro que funcione sobre casi negro.",
    "settings.appearance.logo.favicon": "Favicon",
    "settings.appearance.logo.faviconHint": "Solo isotipo cuadrado. Se muestra a 16px, así que un logotipo con texto se vuelve ilegible.",
    "settings.appearance.logo.upload": "Subir",
    "settings.appearance.logo.replace": "Reemplazar",
    "settings.appearance.logo.remove": "Quitar",
    "settings.appearance.logo.none": "Ninguno",
    "settings.appearance.color.title": "Color",
    "settings.appearance.color.body": "Dos matices y dos niveles de croma. Cada superficie, paso de texto, paso de gráfica y color de estado se calcula a partir de estos, en ambos temas.",
    "settings.appearance.color.accentHue": "Matiz del acento",
    "settings.appearance.color.accentChroma": "Croma del acento",
    "settings.appearance.color.neutralHue": "Matiz neutro",
    "settings.appearance.color.neutralChroma": "Croma neutro",
    "settings.appearance.color.semanticChroma": "Croma semántico",
    "settings.appearance.color.semanticHint": "Controla la intensidad de los colores de éxito, advertencia y error. Sus matices no cambian.",
    "settings.appearance.color.success": "Éxito",
    "settings.appearance.color.warning": "Advertencia",
    "settings.appearance.color.error": "Error",
    "settings.appearance.color.hue": "Matiz {n}",
    "settings.appearance.color.chroma": "Croma {n}",
    "settings.appearance.color.neutralHueSwatch": "Matiz neutro {n}",
    "settings.appearance.color.neutralChromaSwatch": "Croma neutro {n}",
    "settings.appearance.contrast.title": "El contraste no alcanza con estos valores",
    "settings.appearance.contrast.line": "{pair}, tema {mode}: {ratio}:1 (mínimo {minimum}:1)",
    "settings.appearance.contrast.pair.inkOnAccent": "Texto del botón sobre el acento",
    "settings.appearance.contrast.pair.accentTextOnCard": "Acento como texto sobre tarjeta",
    "settings.appearance.contrast.mode.light": "claro",
    "settings.appearance.contrast.mode.dark": "oscuro",
    "settings.appearance.type.title": "Tipografía",
    "settings.appearance.type.body": "Los tamaños y el tracking los fija el sistema. La marca entrega las tipografías y los dos pesos de énfasis.",
    "settings.appearance.type.display": "Títulos y texto",
    "settings.appearance.type.mono": "Mono",
    "settings.appearance.type.bold": "Peso bold",
    "settings.appearance.type.semibold": "Peso semibold",
    "settings.appearance.shape.title": "Forma",
    "settings.appearance.shape.tag": "Ajuste de interfaz",
    "settings.appearance.shape.body": "Tres radios: paneles exteriores, paneles interiores, controles. Cambiarlos cambia el producto, no la marca; muévelos con intención.",
    "settings.appearance.preview.light": "Claro",
    "settings.appearance.preview.dark": "Oscuro",
    "settings.appearance.preview.live": "Vista previa",
    "settings.appearance.preview.logoAlt": "Logo para fondo {ground}",
    "settings.appearance.preview.primary": "Primario",
    "settings.appearance.preview.secondary": "Secundario",
    "settings.appearance.preview.settled": "Liquidado",
    "settings.appearance.preview.waiting": "En espera",
    "settings.appearance.preview.failed": "Fallido",
    "settings.appearance.presets": "Preajustes",
    "settings.appearance.preset.base.hint": "gris frío, azul",
    "settings.appearance.preset.electric.hint": "casi negro, relleno verde brillante",
    "settings.appearance.preset.green.hint": "salvia, neutros cálidos de bosque",
    "settings.appearance.custom.title": "Personalizado",
    "settings.appearance.custom.hint": "dos valores, el resto se deriva",
    "settings.appearance.custom.accent": "Acento",
    "settings.appearance.custom.neutral": "Gris neutro",
    "settings.appearance.custom.picker": "Selector de color: {seed}",
    "settings.appearance.custom.invalidHex": "Usa un color hex, como #2F4FD0.",
    "settings.appearance.derived": "Cómo se deriva el resto",
    "settings.appearance.derivedBody": "El color se construye en oklch, donde el primer número es la luminosidad percibida. Eso permite que una sola regla sirva para todo matiz en lugar de ajustarse a ojo por marca.",
    "settings.appearance.tokens": "Tokens resueltos",
    "settings.appearance.restore": "Restaurar lo último guardado",
    "settings.appearance.restoreTitle": "Restaura los últimos valores guardados con éxito (no los predeterminados del starter)",
    "settings.appearance.error.notAdmin": "Solo un propietario o administrador puede cambiar la marca del espacio.",
    "settings.appearance.error.appearance": "La apariencia predeterminada debe ser clara, oscura o del sistema.",
    "settings.appearance.error.colorNaN": "Uno de los valores de color no es un número.",
    "settings.appearance.error.font": "Elige una tipografía principal de la lista.",
    "settings.appearance.error.mono": "Elige una tipografía mono de la lista.",
    "settings.appearance.error.bold": "Elige un peso bold de la lista.",
    "settings.appearance.error.semibold": "Elige un peso semibold de la lista.",
    "settings.appearance.error.radii": "Los radios deben ser enteros entre 0 y 34.",
    "settings.appearance.error.saveFailed": "No se pudo guardar; nada cambió. Inténtalo de nuevo.",
    "settings.appearance.error.assetKind": "Tipo de archivo desconocido.",
    "settings.appearance.error.noFile": "Primero elige un archivo.",
    "settings.appearance.error.format": "Ese formato no es compatible; usa SVG o PNG.",
    "settings.appearance.error.tooLarge": "El archivo debe pesar menos de 2 MB.",
    "settings.appearance.error.uploadFailed": "La carga falló; nada cambió.",
    "settings.appearance.error.notLinked": "Se guardó la carga pero no se vinculó; inténtalo de nuevo.",
    "settings.appearance.error.removeFailed": "No se pudo eliminar; inténtalo de nuevo.",

    "settings.team.toast.failed": "Eso no funcionó",
    "settings.team.summary.members.one": "{n} miembro",
    "settings.team.summary.members.other": "{n} miembros",
    "settings.team.summary.admins.one": "{n} administrador",
    "settings.team.summary.admins.other": "{n} administradores",
    "settings.team.summary.invitations.one": "{n} invitación pendiente",
    "settings.team.summary.invitations.other": "{n} invitaciones pendientes",
    "settings.team.summary.yourRole": "tu rol: {role}",
    "settings.team.column.member": "Miembro",
    "settings.team.column.role": "Rol",
    "settings.team.roleFor": "Rol de {email}",
    "settings.team.toast.roleUpdated": "Rol actualizado",
    "settings.team.column.joined": "Ingresó",
    "settings.team.remove.title": "¿Eliminar a {email}?",
    "settings.team.remove.body": "Pierde acceso a este espacio de trabajo de inmediato. Su cuenta y todo lo que creó se conservan, y se le puede invitar de nuevo después.",
    "settings.team.remove.confirm": "Eliminar del espacio",
    "settings.team.remove.cancel": "Conservar",
    "settings.team.remove.label": "Eliminar a {email}",
    "settings.team.toast.memberRemoved": "Miembro eliminado",
    "settings.team.eyebrow": "Espacio de trabajo · personas",
    "settings.team.title": "Equipo y permisos",
    "settings.team.invite": "Invitar miembro",
    "settings.team.empty.title": "Aún no hay miembros",
    "settings.team.empty.body": "Invita a la primera persona a este espacio de trabajo.",
    "settings.team.pending": "Invitaciones pendientes",
    "settings.team.invitedAs": "como {role} · caduca {date}",
    "settings.team.invitedChip": "Invitado",
    "settings.team.toast.resent": "Invitación reenviada; el enlace anterior dejó de funcionar",
    "settings.team.resend": "Reenviar",
    "settings.team.revoke.title": "¿Revocar la invitación de {email}?",
    "settings.team.revoke.body": "El enlace enviado deja de funcionar de inmediato. Puedes invitar de nuevo cuando quieras.",
    "settings.team.revoke.confirm": "Revocar",
    "settings.team.toast.revoked": "Invitación revocada",
    "settings.team.revoke": "Revocar",
    "settings.team.roles.title": "Roles y permisos",
    "settings.team.roles.body": "Los roles controlan qué puede administrar cada persona en este espacio.",
    "settings.team.roles.ownerNote": "El propietario no se puede degradar ni eliminar: un espacio de trabajo siempre conserva un administrador completo.",
    "settings.team.dialog.error": "No se pudo enviar la invitación.",
    "settings.team.dialog.sent": "Invitación enviada a {email}",
    "settings.team.dialog.title": "Invitar al espacio de trabajo",
    "settings.team.dialog.body": "Recibe un correo con la marca y un enlace de un solo uso que inicia su sesión, sin contraseña.",
    "settings.team.dialog.email": "Correo de trabajo",
    "settings.team.dialog.emailPlaceholder": "nombre@empresa.com",
    "settings.team.dialog.role": "Rol",
    "settings.team.dialog.cancel": "Cancelar",
    "settings.team.dialog.sending": "Enviando…",
    "settings.team.dialog.send": "Enviar invitación",
    "settings.team.error.notAdmin": "Solo un propietario o administrador puede invitar personas.",
    "settings.team.error.roleNotAllowed": "Puedes invitar como {allowed}, no como {role}.",
    "settings.team.error.assignNotAllowed": "Puedes asignar {allowed}, no {role}.",
    "settings.team.error.alreadyMember": "{email} ya es miembro de este espacio de trabajo.",
    "settings.team.error.alreadyInvited": "{email} ya tiene una invitación pendiente; reenvíala en su lugar.",
    "settings.team.error.createFailed": "No se pudo crear la invitación. Inténtalo de nuevo.",
    "settings.team.error.emailFailed": "No se pudo enviar el correo.",
    "settings.team.error.gone": "Esa invitación ya no existe.",
    "settings.team.error.notPending": "Solo se pueden reenviar invitaciones pendientes.",
    "settings.team.error.resendFailed": "No se pudo reenviar; revisa tu acceso e inténtalo de nuevo.",
    "settings.team.error.revokeFailed": "No se pudo revocar; quizá ya fue aceptada o ya no existe.",
    "settings.team.error.unknownRole": "Rol desconocido.",
    "settings.team.error.ownerRole": "El rol del propietario no se puede cambiar.",
    "settings.team.error.cannotManage": "No puedes administrar a ese miembro.",
    "settings.team.error.roleUnchanged": "El rol no se cambió; revisa tu acceso.",
    "settings.team.error.ownerRemove": "El propietario no se puede eliminar.",
    "settings.team.error.cannotRemove": "No puedes eliminar a ese miembro.",
    "settings.team.error.ownerLeave": "El propietario no puede salir de su propio espacio de trabajo.",
    "settings.team.error.removeFailed": "El miembro no se eliminó; revisa tu acceso.",
    "settings.team.or": "o",

    "settings.activity.action.all": "Todos los eventos",
    "settings.activity.action.settingsUpdated": "Configuración actualizada",
    "settings.activity.action.brandingUpdated": "Marca actualizada",
    "settings.activity.action.memberAdded": "Miembro agregado",
    "settings.activity.action.roleChanged": "Rol cambiado",
    "settings.activity.action.memberRemoved": "Miembro eliminado",
    "settings.activity.action.invitationCreated": "Invitación creada",
    "settings.activity.action.invitationResent": "Invitación reenviada",
    "settings.activity.action.invitationRevoked": "Invitación revocada",
    "settings.activity.action.invitationAccepted": "Invitación aceptada",
    "settings.activity.action.workspaceCreated": "Espacio de trabajo creado",
    "settings.activity.column.when": "Cuándo",
    "settings.activity.column.event": "Evento",
    "settings.activity.column.summary": "Qué pasó",
    "settings.activity.column.resource": "Recurso",
    "settings.activity.eyebrow": "Espacio de trabajo · auditoría",
    "settings.activity.title": "Actividad",
    "settings.activity.intro": "Cada cambio relevante en este espacio de trabajo · se conserva indefinidamente",
    "settings.activity.search": "Buscar eventos",
    "settings.activity.filter.type": "Tipo de evento",
    "settings.activity.filter.actor": "Autor",
    "settings.activity.filter.everyone": "Todos",
    "settings.activity.empty.title": "Aún no hay actividad",
    "settings.activity.empty.body": "Los cambios relevantes (configuración, miembros, invitaciones) aparecerán aquí conforme ocurran.",
    "settings.activity.detail.actor": "Autor",
    "settings.activity.detail.action": "Acción",
    "settings.activity.detail.resource": "Recurso",
    "settings.activity.detail.label": "Etiqueta",
    "settings.activity.detail.resourceId": "Id del recurso",
    "settings.activity.detail.eventId": "Id del evento",
    "settings.activity.detail.at": "Fecha",
    "settings.activity.detail.title": "Detalle del evento",
    "settings.activity.detail.close": "Cerrar",
    "settings.activity.detail.changed": "Qué cambió",
    "settings.activity.detail.metadata": "Metadatos",
    "settings.activity.detail.context": "Contexto",
    "settings.activity.detail.before": "antes",
    "settings.activity.detail.after": "después",

    "settings.general.eyebrow": "Espacio de trabajo · general",
    "settings.general.title": "General",
    "settings.general.intro": "La identidad del espacio de trabajo y sus valores regionales predeterminados. La identidad visual está en Apariencia y marca.",
    "settings.general.readOnly": "Puedes ver esta configuración, pero solo un propietario o administrador puede cambiarla.",
    "settings.general.status.saving": "Guardando…",
    "settings.general.status.saved": "Guardado",
    "settings.general.status.failed": "No se pudo guardar",
    "settings.general.workspace.title": "Espacio de trabajo",
    "settings.general.workspace.body": "El nombre que se muestra en el shell, en la pestaña del navegador y en los correos de invitación, y los datos que soporte suele pedir.",
    "settings.general.workspace.name": "Nombre del espacio",
    "settings.general.regional.title": "Regional",
    "settings.general.regional.body": "Valores predeterminados para todo el espacio. Cada persona puede elegir su propio idioma desde el menú de cuenta; la zona horaria es compartida.",
    "settings.general.regional.language": "Idioma predeterminado",
    "settings.general.regional.hint": "Aplica a los miembros nuevos, a quien no haya elegido idioma y a las pantallas de acceso e invitación.",
    "settings.general.regional.timeZone": "Zona horaria",
    "settings.general.regional.timeZoneHint": "Las fechas, el “hoy” y los cortes de periodo siguen esta zona para todos, desde donde inicien sesión.",
    "settings.general.regional.sample": "Ahora mismo",
    "settings.general.toast.localeSaved": "Idioma predeterminado actualizado",
    "settings.general.toast.timeZoneSaved": "Zona horaria actualizada",
    "settings.general.toast.roleSaved": "Rol predeterminado actualizado",
    "settings.general.facts.id": "Id del espacio",
    "settings.general.facts.slug": "Slug",
    "settings.general.facts.created": "Creado",
    "settings.general.facts.owner": "Propietario",
    "settings.general.facts.members": "Miembros",
    "settings.general.facts.copy": "Copiar",
    "settings.general.facts.copied": "Copiado",
    "settings.general.facts.copyFailed": "No se pudo copiar; selecciona el id.",
    "settings.general.members.title": "Miembros",
    "settings.general.members.body": "Valores predeterminados para quienes se unen a este espacio. Los roles se administran en Equipo y permisos.",
    "settings.general.members.defaultRole": "Rol predeterminado para invitaciones",
    "settings.general.members.hint": "Viene preseleccionado en el diálogo de invitación; quien invita puede elegir otro rol cada vez.",
    "settings.general.error.invalidTimeZone": "Esa zona horaria no se reconoce.",
    "settings.general.error.invalidRole": "Elige administrador, miembro o lector.",
    "settings.general.error.notAdmin": "Solo un propietario o administrador puede cambiar la configuración general.",
    "settings.general.error.nameRequired": "El espacio de trabajo necesita un nombre.",
    "settings.general.error.nameTooLong": "El nombre debe tener menos de 80 caracteres.",
    "settings.general.error.invalidLocale": "Ese idioma no está disponible.",
    "settings.general.error.saveFailed": "No se pudo guardar; nada cambió. Inténtalo de nuevo.",
    "settings.emails.eyebrow": "Espacio de trabajo · correo transaccional",
    "settings.emails.title": "Correos",
    "settings.emails.intro": "Cada mensaje que envía el producto, generado por el mismo código que lo envía. Las palabras vienen del diccionario y los colores de la marca, así que lo que ves aquí es lo que llega a la bandeja de entrada.",
    "settings.emails.group.authentication": "Autenticación",
    "settings.emails.group.membership": "Membresía",
    "settings.emails.template.magicLink": "Enlace de acceso",
    "settings.emails.template.invitation": "Invitación al espacio",
    "settings.emails.kind.supabase": "Transaccional · lo entrega Supabase Auth",
    "settings.emails.kind.resend": "Transaccional · lo envía la aplicación",
    "settings.emails.view.preview": "Vista previa",
    "settings.emails.view.html": "HTML",
    "settings.emails.view.text": "Texto simple",
    "settings.emails.width.desktop": "Escritorio",
    "settings.emails.width.mobile": "Móvil",
    "settings.emails.mode.light": "Claro",
    "settings.emails.mode.dark": "Oscuro",
    "settings.emails.chrome.from": "De",
    "settings.emails.sendDetails": "Detalles del envío",
    "settings.emails.metaLabel.trigger": "Disparador",
    "settings.emails.metaLabel.delay": "Retraso",
    "settings.emails.metaLabel.expiry": "Caducidad",
    "settings.emails.metaLabel.delivery": "Entrega",
    "settings.emails.metaValue.signInRequested": "se pidió acceso",
    "settings.emails.metaValue.invitationSent": "se envió una invitación",
    "settings.emails.metaValue.immediate": "inmediato",
    "settings.emails.metaValue.magicLink": "15 minutos",
    "settings.emails.metaValue.invitation": "7 días",
    "settings.emails.metaValue.supabase": "Supabase Auth",
    "settings.emails.metaValue.resend": "Resend",
    "settings.emails.detail.language": "Idioma",
    "settings.emails.detail.branding": "Marca",
    "settings.emails.detail.sender": "Remitente",
    "settings.emails.detail.subject": "Asunto",
    "settings.emails.detail.preheader": "Línea de vista previa",
    "settings.emails.branding.workspace": "Este espacio de trabajo",
    "settings.emails.branding.project": "Predeterminado del proyecto",
    "settings.emails.brandingNote": "El correo de acceso no tiene espacio de trabajo: quien lo recibe puede no pertenecer a ninguno todavía. Lleva la marca y el idioma del proyecto definidos en src/config/project.ts y viaja como plantilla estática, regenerada con pnpm build:auth-emails y publicada junto con la configuración de Supabase.",
    "settings.emails.blocks": "Bloques de este correo",
    "settings.emails.block.brand": "Fila de marca",
    "settings.emails.block.badge": "Distintivo de estado",
    "settings.emails.block.heading": "Título",
    "settings.emails.block.paragraph": "Cuerpo",
    "settings.emails.block.code": "Bloque de código",
    "settings.emails.block.button": "Botón",
    "settings.emails.block.fallback": "URL de respaldo",
    "settings.emails.block.rows": "Tabla de detalles",
    "settings.emails.block.callout": "Aviso",
    "settings.emails.block.secondary": "Letra pequeña",
    "settings.emails.block.footer": "Pie",
    "settings.emails.rules": "Reglas de todo envío",
    "settings.emails.rule.1": "Un solo objetivo por correo. Si necesita dos botones, son dos correos.",
    "settings.emails.rule.2": "El asunto lleva el hecho, no un anzuelo. Debe bastar la notificación para poder actuar.",
    "settings.emails.rule.3": "Todo enlace lleva su URL en texto plano: los clientes corporativos eliminan los botones.",
    "settings.emails.rule.4": "Explica siempre en el pie por qué recibieron el correo.",
    "settings.emails.rule.5": "Sin propiedades personalizadas ni CSS externo. Los colores son hex literales resueltos desde la marca al momento de enviar.",
    "settings.emails.rule.6": "620px de ancho, una sola columna, cuerpo de 15px. Menos de 380px es un teléfono y se apila.",
    "settings.emails.rule.7": "El correo programado se puede cancelar; el transaccional no, y no debe fingir que sí.",
    "settings.emails.tokens": "Tokens del correo",
    "settings.emails.tokensBody": "Los clientes de correo eliminan las propiedades personalizadas, así que estos valores se resuelven a literales al momento de enviar, desde la misma marca que usa el producto.",
    "settings.emails.token.ground": "fuera de la tarjeta",
    "settings.emails.token.card": "el correo en sí",
    "settings.emails.token.inset": "tablas, código",
    "settings.emails.token.accent": "botones, enlaces",
    "settings.emails.token.ink": "títulos",
    "settings.emails.token.ink2": "texto del cuerpo",
    "settings.emails.copy": "Copiar",
    "settings.emails.copied": "Copiado",
    "settings.emails.copyFailed": "No se pudo copiar",
  },
})
