// Relative .ts import keeps this module runnable under `node --test`.
import { defineCopy } from "../../core/i18n/t.ts"

/**
 * Settings module copy (general, appearance, team, activity). English is
 * the source; es-MX follows sentence case. Keys are English identifiers
 * under `settings.`; components resolve them with `useT(settingsCopy)`.
 */
export const settingsCopy = defineCopy({
  en: {
    "settings.appearance.toast.uploadFailed": "Upload failed",
    "settings.appearance.toast.faviconUpdated": "Favicon updated",
    "settings.appearance.toast.logoUpdated": "Logo updated",
    "settings.appearance.toast.removed": "Removed",
    "settings.appearance.toast.removeFailed": "Could not remove",
    "settings.appearance.eyebrow": "Workspace · brand",
    "settings.appearance.title": "Brand",
    "settings.appearance.status.saving": "Saving…",
    "settings.appearance.status.saved": "Saved",
    "settings.appearance.status.failed": "Couldn't save",
    "settings.appearance.readOnly": "You can view these settings, but only an owner or admin can change them.",
    "settings.appearance.mode.title": "Default appearance",
    "settings.appearance.mode.light": "Light",
    "settings.appearance.mode.dark": "Dark",
    "settings.appearance.mode.system": "System",
    "settings.appearance.logo.title": "Logo",
    "settings.appearance.logo.light": "Logo · light ground",
    "settings.appearance.logo.dark": "Logo · dark ground",
    "settings.appearance.logo.favicon": "Favicon",
    "settings.appearance.logo.upload": "Upload",
    "settings.appearance.logo.remove": "Remove",
    "settings.appearance.logo.none": "None",
    "settings.appearance.color.accentLabel": "Accent colour",
    "settings.appearance.color.neutralLabel": "Neutral tone",
    "settings.appearance.color.neutral.warm": "Warm",
    "settings.appearance.color.neutral.cool": "Cool",
    "settings.appearance.color.neutral.neutral": "Neutral",
    "settings.appearance.custom.contrastOk": "Good contrast",
    "settings.appearance.custom.contrastWarnShort": "Low contrast on button text — consider a darker or lighter accent.",
    "settings.appearance.type.title": "Type",
    "settings.appearance.type.display": "Display and body",
    "settings.appearance.type.mono": "Mono",
    "settings.appearance.preview.light": "Light",
    "settings.appearance.preview.dark": "Dark",
    "settings.appearance.preview.live": "Live preview",
    "settings.appearance.preview.toggle": "View in {ground}",
    "settings.appearance.preview.logoAlt": "{ground} ground logo",
    "settings.appearance.preview.primary": "Primary",
    "settings.appearance.preview.secondary": "Secondary",
    "settings.appearance.preview.settled": "Settled",
    "settings.appearance.preview.waiting": "Waiting",
    "settings.appearance.preview.failed": "Failed",
    "settings.appearance.error.notAdmin": "Only an owner or admin can change workspace branding.",
    "settings.appearance.error.appearance": "Default appearance must be light, dark, or system.",
    "settings.appearance.error.colorNaN": "One of the colour values is not a number.",
    "settings.appearance.error.font": "Pick a display face from the list.",
    "settings.appearance.error.mono": "Pick a mono face from the list.",
    "settings.appearance.error.bold": "Pick a bold weight from the list.",
    "settings.appearance.error.semibold": "Pick a semibold weight from the list.",
    "settings.appearance.error.radii": "Radii must be whole numbers between 0 and 34.",
    "settings.appearance.error.saveFailed": "Could not save — nothing was changed. Try again.",
    "settings.appearance.error.assetKind": "Unknown asset kind.",
    "settings.appearance.error.noFile": "Choose a file first.",
    "settings.appearance.error.format": "That format is not supported — use SVG or PNG.",
    "settings.appearance.error.tooLarge": "Keep artwork under 2MB.",
    "settings.appearance.error.uploadFailed": "Upload failed — nothing was changed.",
    "settings.appearance.error.notLinked": "Upload stored but not linked — try again.",
    "settings.appearance.error.removeFailed": "Could not remove — try again.",

    "settings.team.toast.failed": "That did not work",
    "settings.team.summary.members.one": "{n} member",
    "settings.team.summary.members.other": "{n} members",
    "settings.team.summary.admins.one": "{n} admin",
    "settings.team.summary.admins.other": "{n} admins",
    "settings.team.summary.invitations.one": "{n} pending invitation",
    "settings.team.summary.invitations.other": "{n} pending invitations",
    "settings.team.summary.yourRole": "your role: {role}",
    "settings.team.column.member": "Member",
    "settings.team.column.role": "Role",
    "settings.team.roleFor": "Role for {email}",
    "settings.team.toast.roleUpdated": "Role updated",
    "settings.team.column.joined": "Joined",
    "settings.team.remove.title": "Remove {email}?",
    "settings.team.remove.body": "They lose access to this workspace immediately. Their account and anything they created stay intact, and they can be invited again later.",
    "settings.team.remove.confirm": "Remove from workspace",
    "settings.team.remove.cancel": "Keep them",
    "settings.team.remove.label": "Remove {email}",
    "settings.team.toast.memberRemoved": "Member removed",
    "settings.team.eyebrow": "Workspace · people",
    "settings.team.title": "Team & permissions",
    "settings.team.invite": "Invite member",
    "settings.team.empty.title": "No members yet",
    "settings.team.empty.body": "Invite the first person to this workspace.",
    "settings.team.pending": "Pending invitations",
    "settings.team.invitedAs": "as {role} · expires {date}",
    "settings.team.invitedChip": "Invited",
    "settings.team.toast.resent": "Invitation resent — the old link stopped working",
    "settings.team.resend": "Resend",
    "settings.team.revoke.title": "Revoke the invitation for {email}?",
    "settings.team.revoke.body": "The emailed link stops working immediately. You can invite them again at any time.",
    "settings.team.revoke.confirm": "Revoke it",
    "settings.team.toast.revoked": "Invitation revoked",
    "settings.team.revoke": "Revoke",
    "settings.team.roles.title": "Roles & permissions",
    "settings.team.roles.body": "Roles control what people can manage in this workspace.",
    "settings.team.roles.ownerNote": "The owner cannot be demoted or removed — a workspace always keeps a full administrator.",
    "settings.team.dialog.error": "Could not send the invitation.",
    "settings.team.dialog.sent": "Invitation sent to {email}",
    "settings.team.dialog.title": "Invite to the workspace",
    "settings.team.dialog.body": "They get a branded email with a single-use link that signs them in — no password.",
    "settings.team.dialog.email": "Work email",
    "settings.team.dialog.emailPlaceholder": "name@company.com",
    "settings.team.dialog.role": "Role",
    "settings.team.dialog.cancel": "Cancel",
    "settings.team.dialog.sending": "Sending…",
    "settings.team.dialog.send": "Send invite",
    "settings.team.error.notAdmin": "Only an owner or admin can invite people.",
    "settings.team.error.roleNotAllowed": "You can invite people as {allowed} — not {role}.",
    "settings.team.error.assignNotAllowed": "You can assign {allowed} — not {role}.",
    "settings.team.error.alreadyMember": "{email} is already a member of this workspace.",
    "settings.team.error.alreadyInvited": "{email} already has a pending invitation — resend it instead.",
    "settings.team.error.createFailed": "Could not create the invitation. Try again.",
    "settings.team.error.emailFailed": "The email could not be sent.",
    "settings.team.error.gone": "That invitation no longer exists.",
    "settings.team.error.notPending": "Only pending invitations can be resent.",
    "settings.team.error.resendFailed": "Could not resend — check your access and try again.",
    "settings.team.error.revokeFailed": "Could not revoke — it may already be accepted or gone.",
    "settings.team.error.unknownRole": "Unknown role.",
    "settings.team.error.ownerRole": "The owner's role cannot be changed.",
    "settings.team.error.cannotManage": "You cannot manage that member.",
    "settings.team.error.roleUnchanged": "The role was not changed — check your access.",
    "settings.team.error.ownerRemove": "The owner cannot be removed.",
    "settings.team.error.cannotRemove": "You cannot remove that member.",
    "settings.team.error.ownerLeave": "The owner cannot leave their own workspace.",
    "settings.team.error.removeFailed": "The member was not removed — check your access.",
    "settings.team.or": "or",

    "settings.activity.action.all": "All events",
    "settings.activity.action.settingsUpdated": "Settings updated",
    "settings.activity.action.brandingUpdated": "Branding updated",
    "settings.activity.action.memberAdded": "Member added",
    "settings.activity.action.roleChanged": "Role changed",
    "settings.activity.action.memberRemoved": "Member removed",
    "settings.activity.action.invitationCreated": "Invitation created",
    "settings.activity.action.invitationResent": "Invitation resent",
    "settings.activity.action.invitationRevoked": "Invitation revoked",
    "settings.activity.action.invitationAccepted": "Invitation accepted",
    "settings.activity.action.workspaceCreated": "Workspace created",
    "settings.activity.column.when": "When",
    "settings.activity.column.event": "Event",
    "settings.activity.column.summary": "What happened",
    "settings.activity.column.resource": "Resource",
    "settings.activity.eyebrow": "Workspace · audit",
    "settings.activity.title": "Activity",
    "settings.activity.intro": "Every meaningful change in this workspace · retained indefinitely",
    "settings.activity.search": "Search events",
    "settings.activity.filter.type": "Event type",
    "settings.activity.filter.actor": "Actor",
    "settings.activity.filter.everyone": "Everyone",
    "settings.activity.empty.title": "No activity yet",
    "settings.activity.empty.body": "Meaningful changes — settings, members, invitations — will appear here as they happen.",
    "settings.activity.detail.actor": "Actor",
    "settings.activity.detail.action": "Action",
    "settings.activity.detail.resource": "Resource",
    "settings.activity.detail.label": "Label",
    "settings.activity.detail.resourceId": "Resource id",
    "settings.activity.detail.eventId": "Event id",
    "settings.activity.detail.at": "At",
    "settings.activity.detail.title": "Event detail",
    "settings.activity.detail.close": "Close",
    "settings.activity.detail.changed": "What changed",
    "settings.activity.detail.metadata": "Metadata",
    "settings.activity.detail.context": "Context",
    "settings.activity.detail.before": "before",
    "settings.activity.detail.after": "after",

    "settings.general.eyebrow": "Workspace · general",
    "settings.general.title": "General",
    "settings.general.readOnly": "You can view these settings, but only an owner or admin can change them.",
    "settings.general.status.saving": "Saving…",
    "settings.general.status.saved": "Saved",
    "settings.general.status.failed": "Couldn't save",
    "settings.general.workspace.title": "Workspace",
    "settings.general.workspace.name": "Workspace name",
    "settings.general.regional.title": "Regional",
    "settings.general.regional.language": "Default language",
    "settings.general.regional.hint": "Applies to new members, to anyone who has not chosen a language, and to the sign-in and invitation screens.",
    "settings.general.regional.timeZone": "Time zone",
    "settings.general.regional.timeZoneHint": "Dates, “today”, and period boundaries follow this zone for everyone, wherever they sign in from.",
    "settings.general.regional.sample": "Right now",
    "settings.general.toast.localeSaved": "Default language updated",
    "settings.general.toast.timeZoneSaved": "Time zone updated",
    "settings.general.toast.roleSaved": "Default role updated",
    "settings.general.facts.id": "Workspace id",
    "settings.general.facts.slug": "Slug",
    "settings.general.facts.created": "Created",
    "settings.general.facts.owner": "Owner",
    "settings.general.facts.members": "Members",
    "settings.general.facts.copy": "Copy",
    "settings.general.facts.copied": "Copied",
    "settings.general.facts.copyFailed": "Could not copy — select the id instead.",
    "settings.general.members.title": "Members",
    "settings.general.members.defaultRole": "Default role for invitations",
    "settings.general.members.hint": "Pre-selected in the invite dialog; the inviter can still pick another role each time.",
    "settings.general.brand.title": "Brand",
    "settings.general.brand.current": "Current",
    "settings.general.brand.change": "Edit brand",
    "settings.general.brand.close": "Close",
    "settings.general.error.invalidTimeZone": "That time zone is not recognised.",
    "settings.general.error.invalidRole": "Pick admin, member, or viewer.",
    "settings.general.error.notAdmin": "Only an owner or admin can change general settings.",
    "settings.general.error.nameRequired": "The workspace needs a name.",
    "settings.general.error.nameTooLong": "Keep the workspace name under 80 characters.",
    "settings.general.error.invalidLocale": "That language is not available.",
    "settings.general.error.saveFailed": "Could not save — nothing was changed. Try again.",

    "settings.profile.eyebrow": "Account · profile",
    "settings.profile.title": "Profile",
    "settings.profile.status.saving": "Saving…",
    "settings.profile.status.saved": "Saved",
    "settings.profile.status.failed": "Couldn't save",
    "settings.profile.name": "Name",
    "settings.profile.namePlaceholder": "Your name",
    "settings.profile.email": "Email",
    "settings.profile.photo.title": "Photo",
    "settings.profile.photo.hint": "Square image, shown next to your name across the workspace.",
    "settings.profile.photo.upload": "Upload",
    "settings.profile.photo.remove": "Remove",
    "settings.profile.toast.nameSaved": "Name updated",
    "settings.profile.toast.photoUpdated": "Photo updated",
    "settings.profile.toast.removed": "Removed",
    "settings.profile.toast.uploadFailed": "Upload failed",
    "settings.profile.toast.removeFailed": "Could not remove",
    "settings.profile.error.nameTooLong": "Keep your name under 80 characters.",
    "settings.profile.error.saveFailed": "Could not save — nothing was changed. Try again.",
    "settings.profile.error.noFile": "Choose a file first.",
    "settings.profile.error.format": "That format is not supported — use SVG or PNG.",
    "settings.profile.error.tooLarge": "Keep the photo under 2MB.",
    "settings.profile.error.uploadFailed": "Upload failed — nothing was changed.",
    "settings.profile.error.notLinked": "Upload stored but not linked — try again.",
    "settings.profile.error.removeFailed": "Could not remove — try again.",

    "settings.emails.eyebrow": "Workspace · transactional email",
    "settings.emails.title": "Emails",
    "settings.emails.intro": "Every message this product sends, rendered by the code that sends it. The words come from the dictionary and the colours from the skin, so a preview here is the message that lands in an inbox.",
    "settings.emails.group.authentication": "Authentication",
    "settings.emails.group.membership": "Membership",
    "settings.emails.template.magicLink": "Sign-in link",
    "settings.emails.template.invitation": "Workspace invite",
    "settings.emails.kind.supabase": "Transactional · delivered by Supabase Auth",
    "settings.emails.kind.resend": "Transactional · sent by the app",
    "settings.emails.view.preview": "Preview",
    "settings.emails.view.html": "HTML",
    "settings.emails.view.text": "Plain text",
    "settings.emails.width.desktop": "Desktop",
    "settings.emails.width.mobile": "Mobile",
    "settings.emails.mode.light": "Light",
    "settings.emails.mode.dark": "Dark",
    "settings.emails.chrome.from": "From",
    "settings.emails.sendDetails": "Send details",
    "settings.emails.metaLabel.trigger": "Trigger",
    "settings.emails.metaLabel.delay": "Delay",
    "settings.emails.metaLabel.expiry": "Expiry",
    "settings.emails.metaLabel.delivery": "Delivery",
    "settings.emails.metaValue.signInRequested": "sign-in requested",
    "settings.emails.metaValue.invitationSent": "invitation sent",
    "settings.emails.metaValue.immediate": "immediate",
    "settings.emails.metaValue.magicLink": "15 minutes",
    "settings.emails.metaValue.invitation": "7 days",
    "settings.emails.metaValue.supabase": "Supabase Auth",
    "settings.emails.metaValue.resend": "Resend",
    "settings.emails.detail.language": "Language",
    "settings.emails.detail.branding": "Branding",
    "settings.emails.detail.sender": "Sender",
    "settings.emails.detail.subject": "Subject",
    "settings.emails.detail.preheader": "Preview line",
    "settings.emails.branding.workspace": "This workspace",
    "settings.emails.branding.project": "Project default",
    "settings.emails.brandingNote": "Sign-in mail has no workspace — the recipient may not belong to one yet. It carries the project skin and language from src/config/project.ts and ships as a static template, regenerated with pnpm build:auth-emails and pushed with the Supabase config.",
    "settings.emails.blocks": "Blocks in this email",
    "settings.emails.block.brand": "Brand row",
    "settings.emails.block.badge": "Status badge",
    "settings.emails.block.heading": "Heading",
    "settings.emails.block.paragraph": "Body",
    "settings.emails.block.code": "Code block",
    "settings.emails.block.button": "Button",
    "settings.emails.block.fallback": "URL fallback",
    "settings.emails.block.rows": "Detail table",
    "settings.emails.block.callout": "Callout",
    "settings.emails.block.secondary": "Fine print",
    "settings.emails.block.footer": "Footer",
    "settings.emails.rules": "Rules for every send",
    "settings.emails.rule.1": "One job per email. If it needs two buttons, it is two emails.",
    "settings.emails.rule.2": "The subject carries the fact, not a tease. A person should be able to act from the notification alone.",
    "settings.emails.rule.3": "Every link has a plain-text fallback URL — corporate clients strip buttons.",
    "settings.emails.rule.4": "Say why they received it, every time, in the footer.",
    "settings.emails.rule.5": "No custom properties, no external CSS. Colours are literal hex values resolved from the skin at send time.",
    "settings.emails.rule.6": "620px wide, single column, 15px body. Anything narrower than 380px is a phone and stacks.",
    "settings.emails.rule.7": "Scheduled mail can be unsubscribed; transactional mail cannot, and must not pretend otherwise.",
    "settings.emails.tokens": "Email tokens",
    "settings.emails.tokensBody": "Mail clients strip custom properties, so these are resolved to literal values at send time from the same skin the product uses.",
    "settings.emails.token.ground": "outside the card",
    "settings.emails.token.card": "the email itself",
    "settings.emails.token.inset": "tables, code",
    "settings.emails.token.accent": "buttons, links",
    "settings.emails.token.ink": "headings",
    "settings.emails.token.ink2": "body copy",
    "settings.emails.copy": "Copy",
    "settings.emails.copied": "Copied",
    "settings.emails.copyFailed": "Could not copy",
  },
  "es-MX": {
    "settings.appearance.toast.uploadFailed": "La carga falló",
    "settings.appearance.toast.faviconUpdated": "Favicon actualizado",
    "settings.appearance.toast.logoUpdated": "Logo actualizado",
    "settings.appearance.toast.removed": "Eliminado",
    "settings.appearance.toast.removeFailed": "No se pudo eliminar",
    "settings.appearance.eyebrow": "Espacio de trabajo · marca",
    "settings.appearance.title": "Marca",
    "settings.appearance.status.saving": "Guardando…",
    "settings.appearance.status.saved": "Guardado",
    "settings.appearance.status.failed": "No se pudo guardar",
    "settings.appearance.readOnly": "Puedes ver esta configuración, pero solo un propietario o administrador puede cambiarla.",
    "settings.appearance.mode.title": "Apariencia predeterminada",
    "settings.appearance.mode.light": "Claro",
    "settings.appearance.mode.dark": "Oscuro",
    "settings.appearance.mode.system": "Sistema",
    "settings.appearance.logo.title": "Logo",
    "settings.appearance.logo.light": "Logo · fondo claro",
    "settings.appearance.logo.dark": "Logo · fondo oscuro",
    "settings.appearance.logo.favicon": "Favicon",
    "settings.appearance.logo.upload": "Subir",
    "settings.appearance.logo.remove": "Quitar",
    "settings.appearance.logo.none": "Ninguno",
    "settings.appearance.color.accentLabel": "Color de acento",
    "settings.appearance.color.neutralLabel": "Tono neutro",
    "settings.appearance.color.neutral.warm": "Cálido",
    "settings.appearance.color.neutral.cool": "Frío",
    "settings.appearance.color.neutral.neutral": "Neutro",
    "settings.appearance.custom.contrastOk": "Buen contraste",
    "settings.appearance.custom.contrastWarnShort": "Contraste bajo en el texto del botón — prueba un acento más oscuro o más claro.",
    "settings.appearance.type.title": "Tipografía",
    "settings.appearance.type.display": "Títulos y texto",
    "settings.appearance.type.mono": "Mono",
    "settings.appearance.preview.light": "Claro",
    "settings.appearance.preview.dark": "Oscuro",
    "settings.appearance.preview.live": "Vista previa",
    "settings.appearance.preview.toggle": "Ver en {ground}",
    "settings.appearance.preview.logoAlt": "Logo para fondo {ground}",
    "settings.appearance.preview.primary": "Primario",
    "settings.appearance.preview.secondary": "Secundario",
    "settings.appearance.preview.settled": "Liquidado",
    "settings.appearance.preview.waiting": "En espera",
    "settings.appearance.preview.failed": "Fallido",
    "settings.appearance.error.notAdmin": "Solo un propietario o administrador puede cambiar la marca del espacio.",
    "settings.appearance.error.appearance": "La apariencia predeterminada debe ser clara, oscura o del sistema.",
    "settings.appearance.error.colorNaN": "Uno de los valores de color no es un número.",
    "settings.appearance.error.font": "Elige una tipografía principal de la lista.",
    "settings.appearance.error.mono": "Elige una tipografía mono de la lista.",
    "settings.appearance.error.bold": "Elige un peso bold de la lista.",
    "settings.appearance.error.semibold": "Elige un peso semibold de la lista.",
    "settings.appearance.error.radii": "Los radios deben ser enteros entre 0 y 34.",
    "settings.appearance.error.saveFailed": "No se pudo guardar; nada cambió. Inténtalo de nuevo.",
    "settings.appearance.error.assetKind": "Tipo de archivo desconocido.",
    "settings.appearance.error.noFile": "Primero elige un archivo.",
    "settings.appearance.error.format": "Ese formato no es compatible; usa SVG o PNG.",
    "settings.appearance.error.tooLarge": "El archivo debe pesar menos de 2 MB.",
    "settings.appearance.error.uploadFailed": "La carga falló; nada cambió.",
    "settings.appearance.error.notLinked": "Se guardó la carga pero no se vinculó; inténtalo de nuevo.",
    "settings.appearance.error.removeFailed": "No se pudo eliminar; inténtalo de nuevo.",

    "settings.team.toast.failed": "Eso no funcionó",
    "settings.team.summary.members.one": "{n} miembro",
    "settings.team.summary.members.other": "{n} miembros",
    "settings.team.summary.admins.one": "{n} administrador",
    "settings.team.summary.admins.other": "{n} administradores",
    "settings.team.summary.invitations.one": "{n} invitación pendiente",
    "settings.team.summary.invitations.other": "{n} invitaciones pendientes",
    "settings.team.summary.yourRole": "tu rol: {role}",
    "settings.team.column.member": "Miembro",
    "settings.team.column.role": "Rol",
    "settings.team.roleFor": "Rol de {email}",
    "settings.team.toast.roleUpdated": "Rol actualizado",
    "settings.team.column.joined": "Ingresó",
    "settings.team.remove.title": "¿Eliminar a {email}?",
    "settings.team.remove.body": "Pierde acceso a este espacio de trabajo de inmediato. Su cuenta y todo lo que creó se conservan, y se le puede invitar de nuevo después.",
    "settings.team.remove.confirm": "Eliminar del espacio",
    "settings.team.remove.cancel": "Conservar",
    "settings.team.remove.label": "Eliminar a {email}",
    "settings.team.toast.memberRemoved": "Miembro eliminado",
    "settings.team.eyebrow": "Espacio de trabajo · personas",
    "settings.team.title": "Equipo y permisos",
    "settings.team.invite": "Invitar miembro",
    "settings.team.empty.title": "Aún no hay miembros",
    "settings.team.empty.body": "Invita a la primera persona a este espacio de trabajo.",
    "settings.team.pending": "Invitaciones pendientes",
    "settings.team.invitedAs": "como {role} · caduca {date}",
    "settings.team.invitedChip": "Invitado",
    "settings.team.toast.resent": "Invitación reenviada; el enlace anterior dejó de funcionar",
    "settings.team.resend": "Reenviar",
    "settings.team.revoke.title": "¿Revocar la invitación de {email}?",
    "settings.team.revoke.body": "El enlace enviado deja de funcionar de inmediato. Puedes invitar de nuevo cuando quieras.",
    "settings.team.revoke.confirm": "Revocar",
    "settings.team.toast.revoked": "Invitación revocada",
    "settings.team.revoke": "Revocar",
    "settings.team.roles.title": "Roles y permisos",
    "settings.team.roles.body": "Los roles controlan qué puede administrar cada persona en este espacio.",
    "settings.team.roles.ownerNote": "El propietario no se puede degradar ni eliminar: un espacio de trabajo siempre conserva un administrador completo.",
    "settings.team.dialog.error": "No se pudo enviar la invitación.",
    "settings.team.dialog.sent": "Invitación enviada a {email}",
    "settings.team.dialog.title": "Invitar al espacio de trabajo",
    "settings.team.dialog.body": "Recibe un correo con la marca y un enlace de un solo uso que inicia su sesión, sin contraseña.",
    "settings.team.dialog.email": "Correo de trabajo",
    "settings.team.dialog.emailPlaceholder": "nombre@empresa.com",
    "settings.team.dialog.role": "Rol",
    "settings.team.dialog.cancel": "Cancelar",
    "settings.team.dialog.sending": "Enviando…",
    "settings.team.dialog.send": "Enviar invitación",
    "settings.team.error.notAdmin": "Solo un propietario o administrador puede invitar personas.",
    "settings.team.error.roleNotAllowed": "Puedes invitar como {allowed}, no como {role}.",
    "settings.team.error.assignNotAllowed": "Puedes asignar {allowed}, no {role}.",
    "settings.team.error.alreadyMember": "{email} ya es miembro de este espacio de trabajo.",
    "settings.team.error.alreadyInvited": "{email} ya tiene una invitación pendiente; reenvíala en su lugar.",
    "settings.team.error.createFailed": "No se pudo crear la invitación. Inténtalo de nuevo.",
    "settings.team.error.emailFailed": "No se pudo enviar el correo.",
    "settings.team.error.gone": "Esa invitación ya no existe.",
    "settings.team.error.notPending": "Solo se pueden reenviar invitaciones pendientes.",
    "settings.team.error.resendFailed": "No se pudo reenviar; revisa tu acceso e inténtalo de nuevo.",
    "settings.team.error.revokeFailed": "No se pudo revocar; quizá ya fue aceptada o ya no existe.",
    "settings.team.error.unknownRole": "Rol desconocido.",
    "settings.team.error.ownerRole": "El rol del propietario no se puede cambiar.",
    "settings.team.error.cannotManage": "No puedes administrar a ese miembro.",
    "settings.team.error.roleUnchanged": "El rol no se cambió; revisa tu acceso.",
    "settings.team.error.ownerRemove": "El propietario no se puede eliminar.",
    "settings.team.error.cannotRemove": "No puedes eliminar a ese miembro.",
    "settings.team.error.ownerLeave": "El propietario no puede salir de su propio espacio de trabajo.",
    "settings.team.error.removeFailed": "El miembro no se eliminó; revisa tu acceso.",
    "settings.team.or": "o",

    "settings.activity.action.all": "Todos los eventos",
    "settings.activity.action.settingsUpdated": "Configuración actualizada",
    "settings.activity.action.brandingUpdated": "Marca actualizada",
    "settings.activity.action.memberAdded": "Miembro agregado",
    "settings.activity.action.roleChanged": "Rol cambiado",
    "settings.activity.action.memberRemoved": "Miembro eliminado",
    "settings.activity.action.invitationCreated": "Invitación creada",
    "settings.activity.action.invitationResent": "Invitación reenviada",
    "settings.activity.action.invitationRevoked": "Invitación revocada",
    "settings.activity.action.invitationAccepted": "Invitación aceptada",
    "settings.activity.action.workspaceCreated": "Espacio de trabajo creado",
    "settings.activity.column.when": "Cuándo",
    "settings.activity.column.event": "Evento",
    "settings.activity.column.summary": "Qué pasó",
    "settings.activity.column.resource": "Recurso",
    "settings.activity.eyebrow": "Espacio de trabajo · auditoría",
    "settings.activity.title": "Actividad",
    "settings.activity.intro": "Cada cambio relevante en este espacio de trabajo · se conserva indefinidamente",
    "settings.activity.search": "Buscar eventos",
    "settings.activity.filter.type": "Tipo de evento",
    "settings.activity.filter.actor": "Autor",
    "settings.activity.filter.everyone": "Todos",
    "settings.activity.empty.title": "Aún no hay actividad",
    "settings.activity.empty.body": "Los cambios relevantes (configuración, miembros, invitaciones) aparecerán aquí conforme ocurran.",
    "settings.activity.detail.actor": "Autor",
    "settings.activity.detail.action": "Acción",
    "settings.activity.detail.resource": "Recurso",
    "settings.activity.detail.label": "Etiqueta",
    "settings.activity.detail.resourceId": "Id del recurso",
    "settings.activity.detail.eventId": "Id del evento",
    "settings.activity.detail.at": "Fecha",
    "settings.activity.detail.title": "Detalle del evento",
    "settings.activity.detail.close": "Cerrar",
    "settings.activity.detail.changed": "Qué cambió",
    "settings.activity.detail.metadata": "Metadatos",
    "settings.activity.detail.context": "Contexto",
    "settings.activity.detail.before": "antes",
    "settings.activity.detail.after": "después",

    "settings.general.eyebrow": "Espacio de trabajo · general",
    "settings.general.title": "General",
    "settings.general.readOnly": "Puedes ver esta configuración, pero solo un propietario o administrador puede cambiarla.",
    "settings.general.status.saving": "Guardando…",
    "settings.general.status.saved": "Guardado",
    "settings.general.status.failed": "No se pudo guardar",
    "settings.general.workspace.title": "Espacio de trabajo",
    "settings.general.workspace.name": "Nombre del espacio",
    "settings.general.regional.title": "Regional",
    "settings.general.regional.language": "Idioma predeterminado",
    "settings.general.regional.hint": "Aplica a los miembros nuevos, a quien no haya elegido idioma y a las pantallas de acceso e invitación.",
    "settings.general.regional.timeZone": "Zona horaria",
    "settings.general.regional.timeZoneHint": "Las fechas, el “hoy” y los cortes de periodo siguen esta zona para todos, desde donde inicien sesión.",
    "settings.general.regional.sample": "Ahora mismo",
    "settings.general.toast.localeSaved": "Idioma predeterminado actualizado",
    "settings.general.toast.timeZoneSaved": "Zona horaria actualizada",
    "settings.general.toast.roleSaved": "Rol predeterminado actualizado",
    "settings.general.facts.id": "Id del espacio",
    "settings.general.facts.slug": "Slug",
    "settings.general.facts.created": "Creado",
    "settings.general.facts.owner": "Propietario",
    "settings.general.facts.members": "Miembros",
    "settings.general.facts.copy": "Copiar",
    "settings.general.facts.copied": "Copiado",
    "settings.general.facts.copyFailed": "No se pudo copiar; selecciona el id.",
    "settings.general.members.title": "Miembros",
    "settings.general.members.defaultRole": "Rol predeterminado para invitaciones",
    "settings.general.members.hint": "Viene preseleccionado en el diálogo de invitación; quien invita puede elegir otro rol cada vez.",
    "settings.general.brand.title": "Marca",
    "settings.general.brand.current": "Actual",
    "settings.general.brand.change": "Editar marca",
    "settings.general.brand.close": "Cerrar",
    "settings.general.error.invalidTimeZone": "Esa zona horaria no se reconoce.",
    "settings.general.error.invalidRole": "Elige administrador, miembro o lector.",
    "settings.general.error.notAdmin": "Solo un propietario o administrador puede cambiar la configuración general.",
    "settings.general.error.nameRequired": "El espacio de trabajo necesita un nombre.",
    "settings.general.error.nameTooLong": "El nombre debe tener menos de 80 caracteres.",
    "settings.general.error.invalidLocale": "Ese idioma no está disponible.",
    "settings.general.error.saveFailed": "No se pudo guardar; nada cambió. Inténtalo de nuevo.",

    "settings.profile.eyebrow": "Cuenta · perfil",
    "settings.profile.title": "Perfil",
    "settings.profile.status.saving": "Guardando…",
    "settings.profile.status.saved": "Guardado",
    "settings.profile.status.failed": "No se pudo guardar",
    "settings.profile.name": "Nombre",
    "settings.profile.namePlaceholder": "Tu nombre",
    "settings.profile.email": "Correo",
    "settings.profile.photo.title": "Foto",
    "settings.profile.photo.hint": "Imagen cuadrada, se muestra junto a tu nombre en todo el espacio de trabajo.",
    "settings.profile.photo.upload": "Subir",
    "settings.profile.photo.remove": "Quitar",
    "settings.profile.toast.nameSaved": "Nombre actualizado",
    "settings.profile.toast.photoUpdated": "Foto actualizada",
    "settings.profile.toast.removed": "Eliminado",
    "settings.profile.toast.uploadFailed": "La carga falló",
    "settings.profile.toast.removeFailed": "No se pudo eliminar",
    "settings.profile.error.nameTooLong": "El nombre debe tener menos de 80 caracteres.",
    "settings.profile.error.saveFailed": "No se pudo guardar; nada cambió. Inténtalo de nuevo.",
    "settings.profile.error.noFile": "Primero elige un archivo.",
    "settings.profile.error.format": "Ese formato no es compatible; usa SVG o PNG.",
    "settings.profile.error.tooLarge": "La foto debe pesar menos de 2 MB.",
    "settings.profile.error.uploadFailed": "La carga falló; nada cambió.",
    "settings.profile.error.notLinked": "Se guardó la carga pero no se vinculó; inténtalo de nuevo.",
    "settings.profile.error.removeFailed": "No se pudo eliminar; inténtalo de nuevo.",

    "settings.emails.eyebrow": "Espacio de trabajo · correo transaccional",
    "settings.emails.title": "Correos",
    "settings.emails.intro": "Cada mensaje que envía el producto, generado por el mismo código que lo envía. Las palabras vienen del diccionario y los colores de la marca, así que lo que ves aquí es lo que llega a la bandeja de entrada.",
    "settings.emails.group.authentication": "Autenticación",
    "settings.emails.group.membership": "Membresía",
    "settings.emails.template.magicLink": "Enlace de acceso",
    "settings.emails.template.invitation": "Invitación al espacio",
    "settings.emails.kind.supabase": "Transaccional · lo entrega Supabase Auth",
    "settings.emails.kind.resend": "Transaccional · lo envía la aplicación",
    "settings.emails.view.preview": "Vista previa",
    "settings.emails.view.html": "HTML",
    "settings.emails.view.text": "Texto simple",
    "settings.emails.width.desktop": "Escritorio",
    "settings.emails.width.mobile": "Móvil",
    "settings.emails.mode.light": "Claro",
    "settings.emails.mode.dark": "Oscuro",
    "settings.emails.chrome.from": "De",
    "settings.emails.sendDetails": "Detalles del envío",
    "settings.emails.metaLabel.trigger": "Disparador",
    "settings.emails.metaLabel.delay": "Retraso",
    "settings.emails.metaLabel.expiry": "Caducidad",
    "settings.emails.metaLabel.delivery": "Entrega",
    "settings.emails.metaValue.signInRequested": "se pidió acceso",
    "settings.emails.metaValue.invitationSent": "se envió una invitación",
    "settings.emails.metaValue.immediate": "inmediato",
    "settings.emails.metaValue.magicLink": "15 minutos",
    "settings.emails.metaValue.invitation": "7 días",
    "settings.emails.metaValue.supabase": "Supabase Auth",
    "settings.emails.metaValue.resend": "Resend",
    "settings.emails.detail.language": "Idioma",
    "settings.emails.detail.branding": "Marca",
    "settings.emails.detail.sender": "Remitente",
    "settings.emails.detail.subject": "Asunto",
    "settings.emails.detail.preheader": "Línea de vista previa",
    "settings.emails.branding.workspace": "Este espacio de trabajo",
    "settings.emails.branding.project": "Predeterminado del proyecto",
    "settings.emails.brandingNote": "El correo de acceso no tiene espacio de trabajo: quien lo recibe puede no pertenecer a ninguno todavía. Lleva la marca y el idioma del proyecto definidos en src/config/project.ts y viaja como plantilla estática, regenerada con pnpm build:auth-emails y publicada junto con la configuración de Supabase.",
    "settings.emails.blocks": "Bloques de este correo",
    "settings.emails.block.brand": "Fila de marca",
    "settings.emails.block.badge": "Distintivo de estado",
    "settings.emails.block.heading": "Título",
    "settings.emails.block.paragraph": "Cuerpo",
    "settings.emails.block.code": "Bloque de código",
    "settings.emails.block.button": "Botón",
    "settings.emails.block.fallback": "URL de respaldo",
    "settings.emails.block.rows": "Tabla de detalles",
    "settings.emails.block.callout": "Aviso",
    "settings.emails.block.secondary": "Letra pequeña",
    "settings.emails.block.footer": "Pie",
    "settings.emails.rules": "Reglas de todo envío",
    "settings.emails.rule.1": "Un solo objetivo por correo. Si necesita dos botones, son dos correos.",
    "settings.emails.rule.2": "El asunto lleva el hecho, no un anzuelo. Debe bastar la notificación para poder actuar.",
    "settings.emails.rule.3": "Todo enlace lleva su URL en texto plano: los clientes corporativos eliminan los botones.",
    "settings.emails.rule.4": "Explica siempre en el pie por qué recibieron el correo.",
    "settings.emails.rule.5": "Sin propiedades personalizadas ni CSS externo. Los colores son hex literales resueltos desde la marca al momento de enviar.",
    "settings.emails.rule.6": "620px de ancho, una sola columna, cuerpo de 15px. Menos de 380px es un teléfono y se apila.",
    "settings.emails.rule.7": "El correo programado se puede cancelar; el transaccional no, y no debe fingir que sí.",
    "settings.emails.tokens": "Tokens del correo",
    "settings.emails.tokensBody": "Los clientes de correo eliminan las propiedades personalizadas, así que estos valores se resuelven a literales al momento de enviar, desde la misma marca que usa el producto.",
    "settings.emails.token.ground": "fuera de la tarjeta",
    "settings.emails.token.card": "el correo en sí",
    "settings.emails.token.inset": "tablas, código",
    "settings.emails.token.accent": "botones, enlaces",
    "settings.emails.token.ink": "títulos",
    "settings.emails.token.ink2": "texto del cuerpo",
    "settings.emails.copy": "Copiar",
    "settings.emails.copied": "Copiado",
    "settings.emails.copyFailed": "No se pudo copiar",
  },
})
